nginx:
    build: .
    ports:
        - "80:80"
    volumes:
        - ./web:/usr/share/nginx/web
    links:
        - fpm
fpm:
    image: php:7.1.6-fpm
    volumes:
        - ./web:/usr/share/nginx/web
